updateUrl: "https://metalab.at/ibuttons" # MOS REST URL
pricePerMinute: 100 # in Eurocents
externPricePerMinute: 150 # in Eurocents
laserPowerMinimum: 260 # in W
laserStartupTime: 20 # in seconds
powerMeterIP: "laserauth.lan"
password: "*******"
