name: laserauth
description: Laserauth for Metalab.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_constraintlayout: ^1.7.0-stable
  flutter_gpiod: ^0.5.1+5
  http: ^1.2.0
  logging: ^1.2.0
  udev: ^0.0.3
  virtual_keyboard_custom_layout: ^1.0.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/alien-head.png
